// Generated by rstantools.  Do not edit by hand.

/*
    BACTS is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BACTS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with BACTS.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_CombSourceLogist_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_CombSourceLogist");
    reader.add_event(71, 69, "end", "model_CombSourceLogist");
    return reader;
}
template <typename T0__, typename T1__>
typename boost::math::tools::promote_args<T0__, T1__>::type
ll_bern_logitPr(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& y,
                    const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& lp, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 4;
        validate_non_negative_index("pr", "num_elements(y)", num_elements(y));
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> pr(num_elements(y));
        stan::math::initialize(pr, DUMMY_VAR__);
        stan::math::fill(pr, DUMMY_VAR__);
        current_statement_begin__ = 5;
        local_scalar_t__ sum_log_pr(DUMMY_VAR__);
        (void) sum_log_pr;  // dummy to suppress unused var warning
        stan::math::initialize(sum_log_pr, DUMMY_VAR__);
        stan::math::fill(sum_log_pr, DUMMY_VAR__);
        current_statement_begin__ = 6;
        local_scalar_t__ aux(DUMMY_VAR__);
        (void) aux;  // dummy to suppress unused var warning
        stan::math::initialize(aux, DUMMY_VAR__);
        stan::math::fill(aux, DUMMY_VAR__);
        current_statement_begin__ = 7;
        for (int i = 1; i <= num_elements(y); ++i) {
            current_statement_begin__ = 8;
            stan::math::assign(aux, (stan::math::exp(get_base1(lp, i, "lp", 1)) / (1 + stan::math::exp(get_base1(lp, i, "lp", 1)))));
            current_statement_begin__ = 9;
            stan::model::assign(pr, 
                        stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                        ((get_base1(y, i, "y", 1) * stan::math::log(aux)) + ((1 - get_base1(y, i, "y", 1)) * stan::math::log((1 - aux)))), 
                        "assigning variable pr");
        }
        current_statement_begin__ = 11;
        stan::math::assign(sum_log_pr, sum(pr));
        current_statement_begin__ = 12;
        return stan::math::promote_scalar<fun_return_scalar_t__>(sum_log_pr);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct ll_bern_logitPr_functor__ {
    template <typename T0__, typename T1__>
        typename boost::math::tools::promote_args<T0__, T1__>::type
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& y,
                    const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& lp, std::ostream* pstream__) const {
        return ll_bern_logitPr(y, lp, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_CombSourceLogist
  : public stan::model::model_base_crtp<model_CombSourceLogist> {
private:
        int p_v;
        int p_b;
        int p_vo;
        double tau;
        double a_omega;
        double b_omega;
        vector_d eta;
        matrix_d I;
        row_vector_d mu_s_b;
        matrix_d Sigma_s_b;
        double nu_s_b;
        int m_v;
        vector_d y_v;
        matrix_d X_v;
        double alpha;
public:
    model_CombSourceLogist(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_CombSourceLogist(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_CombSourceLogist_namespace::model_CombSourceLogist";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 17;
            context__.validate_dims("data initialization", "p_v", "int", context__.to_vec());
            p_v = int(0);
            vals_i__ = context__.vals_i("p_v");
            pos__ = 0;
            p_v = vals_i__[pos__++];
            check_greater_or_equal(function__, "p_v", p_v, 0);
            current_statement_begin__ = 18;
            context__.validate_dims("data initialization", "p_b", "int", context__.to_vec());
            p_b = int(0);
            vals_i__ = context__.vals_i("p_b");
            pos__ = 0;
            p_b = vals_i__[pos__++];
            check_greater_or_equal(function__, "p_b", p_b, 0);
            current_statement_begin__ = 19;
            context__.validate_dims("data initialization", "p_vo", "int", context__.to_vec());
            p_vo = int(0);
            vals_i__ = context__.vals_i("p_vo");
            pos__ = 0;
            p_vo = vals_i__[pos__++];
            check_greater_or_equal(function__, "p_vo", p_vo, 0);
            current_statement_begin__ = 21;
            context__.validate_dims("data initialization", "tau", "double", context__.to_vec());
            tau = double(0);
            vals_r__ = context__.vals_r("tau");
            pos__ = 0;
            tau = vals_r__[pos__++];
            check_greater_or_equal(function__, "tau", tau, 0);
            current_statement_begin__ = 22;
            context__.validate_dims("data initialization", "a_omega", "double", context__.to_vec());
            a_omega = double(0);
            vals_r__ = context__.vals_r("a_omega");
            pos__ = 0;
            a_omega = vals_r__[pos__++];
            check_greater_or_equal(function__, "a_omega", a_omega, 0);
            current_statement_begin__ = 23;
            context__.validate_dims("data initialization", "b_omega", "double", context__.to_vec());
            b_omega = double(0);
            vals_r__ = context__.vals_r("b_omega");
            pos__ = 0;
            b_omega = vals_r__[pos__++];
            check_greater_or_equal(function__, "b_omega", b_omega, 0);
            current_statement_begin__ = 24;
            validate_non_negative_index("eta", "p_vo", p_vo);
            context__.validate_dims("data initialization", "eta", "vector_d", context__.to_vec(p_vo));
            eta = Eigen::Matrix<double, Eigen::Dynamic, 1>(p_vo);
            vals_r__ = context__.vals_r("eta");
            pos__ = 0;
            size_t eta_j_1_max__ = p_vo;
            for (size_t j_1__ = 0; j_1__ < eta_j_1_max__; ++j_1__) {
                eta(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 25;
            validate_non_negative_index("I", "p_vo", p_vo);
            validate_non_negative_index("I", "p_vo", p_vo);
            context__.validate_dims("data initialization", "I", "matrix_d", context__.to_vec(p_vo,p_vo));
            I = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(p_vo, p_vo);
            vals_r__ = context__.vals_r("I");
            pos__ = 0;
            size_t I_j_2_max__ = p_vo;
            size_t I_j_1_max__ = p_vo;
            for (size_t j_2__ = 0; j_2__ < I_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < I_j_1_max__; ++j_1__) {
                    I(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 26;
            validate_non_negative_index("mu_s_b", "p_b", p_b);
            context__.validate_dims("data initialization", "mu_s_b", "row_vector_d", context__.to_vec(p_b));
            mu_s_b = Eigen::Matrix<double, 1, Eigen::Dynamic>(p_b);
            vals_r__ = context__.vals_r("mu_s_b");
            pos__ = 0;
            size_t mu_s_b_j_1_max__ = p_b;
            for (size_t j_1__ = 0; j_1__ < mu_s_b_j_1_max__; ++j_1__) {
                mu_s_b(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 27;
            validate_non_negative_index("Sigma_s_b", "p_b", p_b);
            validate_non_negative_index("Sigma_s_b", "p_b", p_b);
            context__.validate_dims("data initialization", "Sigma_s_b", "matrix_d", context__.to_vec(p_b,p_b));
            Sigma_s_b = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(p_b, p_b);
            vals_r__ = context__.vals_r("Sigma_s_b");
            pos__ = 0;
            size_t Sigma_s_b_j_2_max__ = p_b;
            size_t Sigma_s_b_j_1_max__ = p_b;
            for (size_t j_2__ = 0; j_2__ < Sigma_s_b_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < Sigma_s_b_j_1_max__; ++j_1__) {
                    Sigma_s_b(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 28;
            context__.validate_dims("data initialization", "nu_s_b", "double", context__.to_vec());
            nu_s_b = double(0);
            vals_r__ = context__.vals_r("nu_s_b");
            pos__ = 0;
            nu_s_b = vals_r__[pos__++];
            check_greater_or_equal(function__, "nu_s_b", nu_s_b, 1);
            current_statement_begin__ = 30;
            context__.validate_dims("data initialization", "m_v", "int", context__.to_vec());
            m_v = int(0);
            vals_i__ = context__.vals_i("m_v");
            pos__ = 0;
            m_v = vals_i__[pos__++];
            check_greater_or_equal(function__, "m_v", m_v, 0);
            current_statement_begin__ = 31;
            validate_non_negative_index("y_v", "m_v", m_v);
            context__.validate_dims("data initialization", "y_v", "vector_d", context__.to_vec(m_v));
            y_v = Eigen::Matrix<double, Eigen::Dynamic, 1>(m_v);
            vals_r__ = context__.vals_r("y_v");
            pos__ = 0;
            size_t y_v_j_1_max__ = m_v;
            for (size_t j_1__ = 0; j_1__ < y_v_j_1_max__; ++j_1__) {
                y_v(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 32;
            validate_non_negative_index("X_v", "m_v", m_v);
            validate_non_negative_index("X_v", "p_v", p_v);
            context__.validate_dims("data initialization", "X_v", "matrix_d", context__.to_vec(m_v,p_v));
            X_v = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(m_v, p_v);
            vals_r__ = context__.vals_r("X_v");
            pos__ = 0;
            size_t X_v_j_2_max__ = p_v;
            size_t X_v_j_1_max__ = m_v;
            for (size_t j_2__ = 0; j_2__ < X_v_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < X_v_j_1_max__; ++j_1__) {
                    X_v(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 33;
            context__.validate_dims("data initialization", "alpha", "double", context__.to_vec());
            alpha = double(0);
            vals_r__ = context__.vals_r("alpha");
            pos__ = 0;
            alpha = vals_r__[pos__++];
            check_greater_or_equal(function__, "alpha", alpha, 0);
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 37;
            validate_non_negative_index("beta_v", "(p_v - 1)", (p_v - 1));
            num_params_r__ += (p_v - 1);
            current_statement_begin__ = 38;
            num_params_r__ += 1;
            current_statement_begin__ = 39;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_CombSourceLogist() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 37;
        if (!(context__.contains_r("beta_v")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta_v missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta_v");
        pos__ = 0U;
        validate_non_negative_index("beta_v", "(p_v - 1)", (p_v - 1));
        context__.validate_dims("parameter initialization", "beta_v", "row_vector_d", context__.to_vec((p_v - 1)));
        Eigen::Matrix<double, 1, Eigen::Dynamic> beta_v((p_v - 1));
        size_t beta_v_j_1_max__ = (p_v - 1);
        for (size_t j_1__ = 0; j_1__ < beta_v_j_1_max__; ++j_1__) {
            beta_v(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.row_vector_unconstrain(beta_v);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta_v: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 38;
        if (!(context__.contains_r("mu")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mu missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mu");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "mu", "double", context__.to_vec());
        double mu(0);
        mu = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(mu);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mu: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 39;
        if (!(context__.contains_r("omega")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable omega missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("omega");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "omega", "double", context__.to_vec());
        double omega(0);
        omega = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, omega);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable omega: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 37;
            Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic> beta_v;
            (void) beta_v;  // dummy to suppress unused var warning
            if (jacobian__)
                beta_v = in__.row_vector_constrain((p_v - 1), lp__);
            else
                beta_v = in__.row_vector_constrain((p_v - 1));
            current_statement_begin__ = 38;
            local_scalar_t__ mu;
            (void) mu;  // dummy to suppress unused var warning
            if (jacobian__)
                mu = in__.scalar_constrain(lp__);
            else
                mu = in__.scalar_constrain();
            current_statement_begin__ = 39;
            local_scalar_t__ omega;
            (void) omega;  // dummy to suppress unused var warning
            if (jacobian__)
                omega = in__.scalar_lb_constrain(0, lp__);
            else
                omega = in__.scalar_lb_constrain(0);
            // transformed parameters
            current_statement_begin__ = 43;
            validate_non_negative_index("lp_v", "m_v", m_v);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> lp_v(m_v);
            stan::math::initialize(lp_v, DUMMY_VAR__);
            stan::math::fill(lp_v, DUMMY_VAR__);
            current_statement_begin__ = 44;
            validate_non_negative_index("Omega", "p_vo", p_vo);
            validate_non_negative_index("Omega", "p_vo", p_vo);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> Omega(p_vo, p_vo);
            stan::math::initialize(Omega, DUMMY_VAR__);
            stan::math::fill(Omega, DUMMY_VAR__);
            current_statement_begin__ = 45;
            validate_non_negative_index("betamu_v", "p_v", p_v);
            Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic> betamu_v(p_v);
            stan::math::initialize(betamu_v, DUMMY_VAR__);
            stan::math::fill(betamu_v, DUMMY_VAR__);
            current_statement_begin__ = 46;
            validate_non_negative_index("beta_b", "p_b", p_b);
            Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic> beta_b(p_b);
            stan::math::initialize(beta_b, DUMMY_VAR__);
            stan::math::fill(beta_b, DUMMY_VAR__);
            current_statement_begin__ = 47;
            validate_non_negative_index("beta_vo", "p_vo", p_vo);
            Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic> beta_vo(p_vo);
            stan::math::initialize(beta_vo, DUMMY_VAR__);
            stan::math::fill(beta_vo, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 49;
            stan::math::assign(betamu_v, append_col(mu, beta_v));
            current_statement_begin__ = 50;
            stan::math::assign(lp_v, multiply(X_v, transpose(betamu_v)));
            current_statement_begin__ = 52;
            stan::math::assign(beta_b, stan::model::rvalue(beta_v, stan::model::cons_list(stan::model::index_min_max(1, p_b), stan::model::nil_index_list()), "beta_v"));
            current_statement_begin__ = 53;
            stan::math::assign(beta_vo, stan::model::rvalue(beta_v, stan::model::cons_list(stan::model::index_min_max((p_b + 1), (p_b + p_vo)), stan::model::nil_index_list()), "beta_v"));
            current_statement_begin__ = 55;
            stan::math::assign(Omega, multiply((1 / stan::math::sqrt(omega)), I));
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 43;
            size_t lp_v_j_1_max__ = m_v;
            for (size_t j_1__ = 0; j_1__ < lp_v_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(lp_v(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: lp_v" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable lp_v: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 44;
            size_t Omega_j_1_max__ = p_vo;
            size_t Omega_j_2_max__ = p_vo;
            for (size_t j_1__ = 0; j_1__ < Omega_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < Omega_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(Omega(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: Omega" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable Omega: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 45;
            size_t betamu_v_j_1_max__ = p_v;
            for (size_t j_1__ = 0; j_1__ < betamu_v_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(betamu_v(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: betamu_v" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable betamu_v: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 46;
            size_t beta_b_j_1_max__ = p_b;
            for (size_t j_1__ = 0; j_1__ < beta_b_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(beta_b(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: beta_b" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable beta_b: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 47;
            size_t beta_vo_j_1_max__ = p_vo;
            for (size_t j_1__ = 0; j_1__ < beta_vo_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(beta_vo(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: beta_vo" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable beta_vo: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            // model body
            current_statement_begin__ = 59;
            lp_accum__.add(gamma_log<propto__>(omega, a_omega, b_omega));
            current_statement_begin__ = 60;
            lp_accum__.add(normal_log<propto__>(mu, 0, (1 / stan::math::sqrt(tau))));
            current_statement_begin__ = 64;
            lp_accum__.add(ll_bern_logitPr(y_v, lp_v, pstream__));
            current_statement_begin__ = 66;
            lp_accum__.add((alpha * multi_student_t_log(beta_b, nu_s_b, mu_s_b, Sigma_s_b)));
            current_statement_begin__ = 68;
            if (as_bool(logical_neq(p_vo, 0))) {
                current_statement_begin__ = 68;
                lp_accum__.add(multi_normal_log(beta_vo, eta, Omega));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("beta_v");
        names__.push_back("mu");
        names__.push_back("omega");
        names__.push_back("lp_v");
        names__.push_back("Omega");
        names__.push_back("betamu_v");
        names__.push_back("beta_b");
        names__.push_back("beta_vo");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back((p_v - 1));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(m_v);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(p_vo);
        dims__.push_back(p_vo);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(p_v);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(p_b);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(p_vo);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_CombSourceLogist_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        Eigen::Matrix<double, 1, Eigen::Dynamic> beta_v = in__.row_vector_constrain((p_v - 1));
        size_t beta_v_j_1_max__ = (p_v - 1);
        for (size_t j_1__ = 0; j_1__ < beta_v_j_1_max__; ++j_1__) {
            vars__.push_back(beta_v(j_1__));
        }
        double mu = in__.scalar_constrain();
        vars__.push_back(mu);
        double omega = in__.scalar_lb_constrain(0);
        vars__.push_back(omega);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 43;
            validate_non_negative_index("lp_v", "m_v", m_v);
            Eigen::Matrix<double, Eigen::Dynamic, 1> lp_v(m_v);
            stan::math::initialize(lp_v, DUMMY_VAR__);
            stan::math::fill(lp_v, DUMMY_VAR__);
            current_statement_begin__ = 44;
            validate_non_negative_index("Omega", "p_vo", p_vo);
            validate_non_negative_index("Omega", "p_vo", p_vo);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> Omega(p_vo, p_vo);
            stan::math::initialize(Omega, DUMMY_VAR__);
            stan::math::fill(Omega, DUMMY_VAR__);
            current_statement_begin__ = 45;
            validate_non_negative_index("betamu_v", "p_v", p_v);
            Eigen::Matrix<double, 1, Eigen::Dynamic> betamu_v(p_v);
            stan::math::initialize(betamu_v, DUMMY_VAR__);
            stan::math::fill(betamu_v, DUMMY_VAR__);
            current_statement_begin__ = 46;
            validate_non_negative_index("beta_b", "p_b", p_b);
            Eigen::Matrix<double, 1, Eigen::Dynamic> beta_b(p_b);
            stan::math::initialize(beta_b, DUMMY_VAR__);
            stan::math::fill(beta_b, DUMMY_VAR__);
            current_statement_begin__ = 47;
            validate_non_negative_index("beta_vo", "p_vo", p_vo);
            Eigen::Matrix<double, 1, Eigen::Dynamic> beta_vo(p_vo);
            stan::math::initialize(beta_vo, DUMMY_VAR__);
            stan::math::fill(beta_vo, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 49;
            stan::math::assign(betamu_v, append_col(mu, beta_v));
            current_statement_begin__ = 50;
            stan::math::assign(lp_v, multiply(X_v, transpose(betamu_v)));
            current_statement_begin__ = 52;
            stan::math::assign(beta_b, stan::model::rvalue(beta_v, stan::model::cons_list(stan::model::index_min_max(1, p_b), stan::model::nil_index_list()), "beta_v"));
            current_statement_begin__ = 53;
            stan::math::assign(beta_vo, stan::model::rvalue(beta_v, stan::model::cons_list(stan::model::index_min_max((p_b + 1), (p_b + p_vo)), stan::model::nil_index_list()), "beta_v"));
            current_statement_begin__ = 55;
            stan::math::assign(Omega, multiply((1 / stan::math::sqrt(omega)), I));
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            // write transformed parameters
            if (include_tparams__) {
                size_t lp_v_j_1_max__ = m_v;
                for (size_t j_1__ = 0; j_1__ < lp_v_j_1_max__; ++j_1__) {
                    vars__.push_back(lp_v(j_1__));
                }
                size_t Omega_j_2_max__ = p_vo;
                size_t Omega_j_1_max__ = p_vo;
                for (size_t j_2__ = 0; j_2__ < Omega_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < Omega_j_1_max__; ++j_1__) {
                        vars__.push_back(Omega(j_1__, j_2__));
                    }
                }
                size_t betamu_v_j_1_max__ = p_v;
                for (size_t j_1__ = 0; j_1__ < betamu_v_j_1_max__; ++j_1__) {
                    vars__.push_back(betamu_v(j_1__));
                }
                size_t beta_b_j_1_max__ = p_b;
                for (size_t j_1__ = 0; j_1__ < beta_b_j_1_max__; ++j_1__) {
                    vars__.push_back(beta_b(j_1__));
                }
                size_t beta_vo_j_1_max__ = p_vo;
                for (size_t j_1__ = 0; j_1__ < beta_vo_j_1_max__; ++j_1__) {
                    vars__.push_back(beta_vo(j_1__));
                }
            }
            if (!include_gqs__) return;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_CombSourceLogist";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t beta_v_j_1_max__ = (p_v - 1);
        for (size_t j_1__ = 0; j_1__ < beta_v_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_v" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "omega";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t lp_v_j_1_max__ = m_v;
            for (size_t j_1__ = 0; j_1__ < lp_v_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "lp_v" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t Omega_j_2_max__ = p_vo;
            size_t Omega_j_1_max__ = p_vo;
            for (size_t j_2__ = 0; j_2__ < Omega_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < Omega_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "Omega" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t betamu_v_j_1_max__ = p_v;
            for (size_t j_1__ = 0; j_1__ < betamu_v_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "betamu_v" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t beta_b_j_1_max__ = p_b;
            for (size_t j_1__ = 0; j_1__ < beta_b_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_b" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t beta_vo_j_1_max__ = p_vo;
            for (size_t j_1__ = 0; j_1__ < beta_vo_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_vo" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t beta_v_j_1_max__ = (p_v - 1);
        for (size_t j_1__ = 0; j_1__ < beta_v_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_v" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "omega";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t lp_v_j_1_max__ = m_v;
            for (size_t j_1__ = 0; j_1__ < lp_v_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "lp_v" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t Omega_j_2_max__ = p_vo;
            size_t Omega_j_1_max__ = p_vo;
            for (size_t j_2__ = 0; j_2__ < Omega_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < Omega_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "Omega" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t betamu_v_j_1_max__ = p_v;
            for (size_t j_1__ = 0; j_1__ < betamu_v_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "betamu_v" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t beta_b_j_1_max__ = p_b;
            for (size_t j_1__ = 0; j_1__ < beta_b_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_b" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t beta_vo_j_1_max__ = p_vo;
            for (size_t j_1__ = 0; j_1__ < beta_vo_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_vo" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
    }
}; // model
}  // namespace
typedef model_CombSourceLogist_namespace::model_CombSourceLogist stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
